# Generated by Django 5.1.4 on 2025-05-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='Rdate',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='msg',
        ),
        migrations.AddField(
            model_name='reminder',
            name='Timer',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='message',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
